### ISSUE TITLE
`mad_ctpsa_rect` calculation

### ISSUE THREAD

**Issue by mattsignorelli** [MethodicalAcceleratorDesign/MAD-NG#418]
For a tpsa `t`, I expected `mad_ctpsa_rect` to calculate `r = CPX(  real(t)*cos(imag(t)) ,  real(t)*sin(imag(t))  )`, however this does not appear to be the case. For scalars as tpsas, `mad_ctpsa_rect` gives:
```
rect(1+1i) = 5.4030230586813977E-01 +4.5464871341284091E-01   # Should be 0.5403023058681398 + 0.8414709848078965i ?
```

**Comment by ldeniau** [comment]
I do not confirm the problem for scalars, I do for TPSA. It could be either an aliasing problem in rect or in sincos.

I will check soon.
