### ISSUE TITLE
`mad_tpsa_deriv` leaving junk for some monomial coefficients

### ISSUE THREAD

**Issue by mattsignorelli** [MethodicalAcceleratorDesign/MAD-NG#421]
Suppose I have a TPSA `a` with 1 variable and say 1 parameter, equal to the sin of the variable to some order. If I make a new TPSA `b` using `mad_tpsa_new` with `MAD_TPSA_SAME` , and then do `mad_tpsa_deriv(a, b, 1)`, `b`  contains a lot of junk along with the non-junk monomials for cos. The junk does not show when doing `mad_tpsa_print`, however it does show when doing `mad_tpsa_cycle` and it propagates through in following calculations (for example `mad_tpsa_nrm(b)` gives `NaN`), which suggests the junk is not accounted for properly, even though it isn't appearing in `mad_tpsa_print`

For example, `mad_tpsa_cycle` for `b` in the above example gives (some junk randomly very large):

```
  Coefficient              Order     Exponents
   1.0000000000000000e+00     0        0   
  7.3981717867857096e-316     1        0    2^1
  -5.0000000000000000e-01     2        2     
  -4.0464605390294736e+307    3        3    
  -8.2275227866058539e+62     3        2    2^1
  7.3981741583008096e-316     3        0    2^3
   4.1666666666666664e-02     4        4    
```

while `mad_tpsa_print` gives:

```
 -UNNAMED-:  R, NV =   1, MO = 10, NP =   1, PO = 10, NO =   5
 *******************************************************
     I   COEFFICIENT             ORDER   EXPONENTS
     1   1.0000000000000000E+00    0     0
     2  -5.0000000000000000E-01    2     2
     3   0.0000000000000000E+00    2     1  2^1
     4   0.0000000000000000E+00    2     0  2^2
     5   4.1666666666666664E-02    4     4
     6   0.0000000000000000E+00    4     3  2^1
     7   0.0000000000000000E+00    4     2  2^2
     8   0.0000000000000000E+00    4     1  2^3
     9   0.0000000000000000E+00    4     0  2^4
```

and `mad_tpsa_nrm(b)` gives `NaN`

**Comment by mattsignorelli** [comment]
I also see the junk with `mad_tpsa_derivm`, and both of their complex counterparts

**Comment by mattsignorelli** [comment]
Also, the junk being so large doesn't happen always, in many cases it is small. Randomly though the junk will be very large and that's when there are problems

**Comment by ldeniau** [comment]
I would need a more precise and complete example, either in MAD-NG or as a sequence of C function calls such that I can reproduce the result. Because the header -UNNAMED-:  R, NV =   1, MO = 10, NP =   1, PO = 10, NO =   5 is invalid as detected by MAD-NG. Second, all the coefficients inside a TPSA are not valid, so scanning the content by hand is not valid. In principle, unless a bug is around, mad_tpsa_print and mad_tpsa_cycle are taking care of this.

d = MAD.gtpsad{nv=1,np=1,mo=10,po=10,no=5}
madl_gtpsa.mad:153: invalid number of orders (#no ~= nv+np)
stack traceback:
	[C]: in function 'assert'
	madl_gtpsa.mad:153: in function 'gtpsad'
	stdin:1: in main chunk
	[C]: at 0x0104dcde40

**Comment by ldeniau** [comment]
Here is an example in MAD-NG:
```
> MAD.gtpsad{nv=1,np=1,mo=10,po=10}
> a=MAD.tpsa():setvar(1,1,1)
> b=a:same()
> c=a:same()
> a:sin(b)
> b:deriv(1,c)
> a:print() ; b:print() ; c:print()

 -UNNAMED-:  R, NV =   1, MO = 10, NP =   1, PO = 10
 *******************************************************
     I   COEFFICIENT             ORDER   EXPONENTS
     1   1.0000000000000000E+00    0     0
     2   1.0000000000000000E+00    1     1

 -UNNAMED-:  R, NV =   1, MO = 10, NP =   1, PO = 10
 *******************************************************
     I   COEFFICIENT             ORDER   EXPONENTS
     1   8.4147098480789650E-01    0     0
     2   5.4030230586813977E-01    1     1
     3  -4.2073549240394825E-01    2     2
     4  -9.0050384311356632E-02    3     3
     5   3.5061291033662352E-02    4     4
     6   4.5025192155678318E-03    5     5
     7  -1.1687097011220783E-03    6     6
     8  -1.0720283846590076E-04    7     7
     9   2.0869816091465686E-05    8     8
    10   1.4889283120263995E-06    9     9
    11  -2.3188684546072984E-07   10     10

 -UNNAMED-:  R, NV =   1, MO = 10, NP =   1, PO = 10
 *******************************************************
     I   COEFFICIENT             ORDER   EXPONENTS
     1   5.4030230586813977E-01    0     0
     2  -8.4147098480789650E-01    1     1
     3  -2.7015115293406988E-01    2     2
     4   1.4024516413464941E-01    3     3
     5   2.2512596077839158E-02    4     4
     6  -7.0122582067324701E-03    5     5
     7  -7.5041986926130530E-04    6     6
     8   1.6695852873172549E-04    7     7
     9   1.3400354808237595E-05    8     8
    10  -2.3188684546072986E-06    9     9

```

**Comment by mattsignorelli** [comment]
Ok, I'll put together an example in C. I had to use `mad_desc_newvpo` to create the Descriptor because the variable maximum order is less than the parameter maximum order (so mo = po). So to create that header my no = [5, 10] in my above example.

**Comment by ldeniau** [comment]
I corrected my previous example to better match what I understand from your first comment

**Comment by mattsignorelli** [comment]
Ah I just saw that, thanks. Yes Etienne is very interested in some analyses where the parameter order is > the variable order, and that was how I was constructing that descriptor. 

In your above example in MAD-NG, repeat everything but set the scalar part of a equal to zero (so it's just sin(x))

**Comment by ldeniau** [comment]
I found that "cycle" does not check for nz so garbage can come from there...

**Comment by ldeniau** [comment]
I fixed "cycle" in 4ab90a68, let me know if it fix also your problem

**Comment by mattsignorelli** [comment]
Ok so `cycle` doesn't up the garbage anymore, however `mad_tpsa_nrm` still picks up this garbage and so occasionally/randomly returns NaNs or something very large.

**Comment by mattsignorelli** [comment]
OK everything looks good now!

**Comment by ldeniau** [comment]
> I also see the junk with `mad_tpsa_derivm`, and both of their complex counterparts

"derive" is taking care of nz, so if the problem is still around, it comes from something else, and I will need a clear standalone example to reproduce it and investigate.
