### ISSUE TITLE
`mad_tpsa_getv`, `getm`, `gets`, etc also should check nz

### ISSUE THREAD

**Issue by mattsignorelli** [MethodicalAcceleratorDesign/MAD-NG#422]
Should all of the monomial getter functions (`getm`,`gets`,`getsm`,`getv`,`geti`, `get0`) also check nz? In the same example I showed earlier, the garbage still appears when using these getter functions

**Comment by ldeniau** [comment]
yes, they should except get0. I will make the fixes soon.

**Comment by ldeniau** [comment]
fixed in fe648247
