### ISSUE TITLE
Result TPSAs must be zero: caused by using `set0` now instead of `setvar`

### ISSUE THREAD

**Issue by mattsignorelli** [MethodicalAcceleratorDesign/MAD-NG#429]
I noticed that `setvar` in many of the functions/operations was replaced with `set0` in the most recent changes. However `set0` does not clear the rest of the values in the tpsa, unlike `setvar`. Therefore the result is incorrect if the result TPSA contains values already (not equal to zero). 

Simple example attached (only show `scl` but all functions where this internal change from `setvar` to `set0` apply)

[bug_inplace.zip](https://github.com/MethodicalAcceleratorDesign/MAD-NG/files/14616608/bug_inplace.zip)

**Comment by ldeniau** [comment]
it seems I forgot the special case of iv=0 that doesn't clean up first-order homogeneous polynomial but just set hi=0, which is equivalent... 
fixed in e8e3e1f6
