### ISSUE TITLE
Bug in __eq for the tpsa and ctpsa

### ISSUE THREAD

**Issue by 17IMMANUEL17** [MethodicalAcceleratorDesign/MAD-NG#438]
Discovered a bug for the equality operator: as for the print function __eq checks the descriptor and not the tpsa. In this way
mo = 4
d = gtpsad(nil,mo)
t1 = tpsa(d)
t2 = tpsa(d,3)
t1==t2 -->true
This should generate an error since the teo tpsas have a different order.
This is due to the fact that the two different tpsas are created using the same descriptor and the check that __eq does to ensure that the comparison is valid is based on the descriptor.

**Comment by ldeniau** [comment]
The result is correct, no bug. The order 3 in t2 is a "local" maximum order limiting size of memory and calculation as an optimisation, not a structural order that makes these tpsas incompatibles. When you print t1 and t2, they both have mo=4 and since they are empty, they have same values.
