### ISSUE TITLE
Bug in __le and __leq for tpsa

### ISSUE THREAD

**Issue by 17IMMANUEL17** [MethodicalAcceleratorDesign/MAD-NG#439]
local d = gtpsad(2,10) 
local t1 = tpsa(d) 
local t2 = tpsa(d,9) 
print(t1<=t2) ---> true

In the code above we create two tpsas from the same descriptor but imposing the maximum order t2 equal to 9. In this way using the __leq (same for __le) sjpuld trigger an error but the ouput is instead true.

local d = gtpsad(2,10) 
local d2 = gtpsad(2,9) 
local t1 = tpsa(d) 
local t2 = tpsa(d2) 
print(t1<=t2) --> 'incompatible GTPSA descriptor'

If we then run this we see the behaviour we should expect.

**Comment by ldeniau** [comment]
The fist case is the same misunderstanding as for issue #438
The second case reports correctly that tpsas are incompatibles because they don't have the same internal structure, i.e. their global mo differ as well as their indexing scheme.
