### ISSUE TITLE
Composition bug crept in on June 20th

### ISSUE THREAD

**Issue by mattsignorelli** [MethodicalAcceleratorDesign/MAD-NG#448]
The bug is in the concatenator, starting from commits on June 20th (my normal form tests no longer pass)

I narrow down the exact commit where the bug appears and reply soon

**Comment by mattsignorelli** [comment]
OK the bug first appears somewhere between commits 661e701 and a9e2781

**Comment by mattsignorelli** [comment]
OK I have a minimal working example. It reveals the bug in the concatenator:

If you do K1 $\circ$ K2, you'll see that the result only contains terms up to order 5, when it should contain terms up to order 6. 

[K1.txt](https://github.com/user-attachments/files/16070601/K1.txt)
[K2.txt](https://github.com/user-attachments/files/16070600/K2.txt)

**Comment by ldeniau** [comment]
fixed in commit #780468a0
Let me know if it works for you.
Thanks!

**Comment by mattsignorelli** [comment]
Looks like this fixes the bug, thanks!
